baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Tika Blog'
[languages]
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    weight = 1

  [languages.id]
    contentDir = 'content/id'
    languageName = 'Bahasa Indonesia'
    weight = 2