name = "blogtika-cloudflare-worker"
compatibility_date = "2025-07-31"

[build]
command = "chmod a+x build.sh && ./build.sh"

[assets]
directory = "./public"
not_found_handling = "404-page"

# Custom domain configuration
routes = [
  { pattern = "blog.tikadata.com/*", zone_name = "tikadata.com" }
]